name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: go fmt
        run: |
          go fmt ./...
          git diff --exit-code
      - run: go vet ./...
      - run: go test ./...
